message( STATUS "------------------ General configuration for ${PROJECT_NAME} ${VERSION} -----------------")
message( STATUS )
message( STATUS "Build mode:                ${CMAKE_BUILD_TYPE}")
message( STATUS "CMake Generator:           ${CMAKE_GENERATOR}")
message( STATUS "Compiler:                  ${CMAKE_CXX_COMPILER_ID}")
message( STATUS "CMAKE_SYSTEM_PROCESSOR=    ${CMAKE_SYSTEM_PROCESSOR}" )
message( STATUS "CMAKE_SYSTEM_VERSION=      ${CMAKE_SYSTEM_VERSION}")
message( STATUS "CMAKE_CXX_COMPILER_ID=     ${CMAKE_CXX_COMPILER_ID}")
message( STATUS "CMAKE_CXX_COMPILER=        ${CMAKE_CXX_COMPILER}")
message( STATUS "CMAKE_CXX_COMPILER_VERSION=${CMAKE_CXX_COMPILER_VERSION}")
message( STATUS "C++ flags (Release):       ${CMAKE_CXX_FLAGS_RELEASE}")
message( STATUS "C++ flags (Debug):         ${CMAKE_CXX_FLAGS_DEBUG}")
message( STATUS "C++ flags (Both):          ${CMAKE_CXX_FLAGS}")
message( STATUS )
message( STATUS "Change a value with: cmake -D<Variable>=<Value>" )
message( STATUS )
